### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/projthis#1]
Hi @elikesprogramming, @jennybc, @malcolmbarrett:

Given the discussion in usethis, I thought to make a toy package to test out ideas in relative isolation.

I don't know if these ideas ultimately make their way either to renv or usethis, or if it makes sense for this to be its own thing.

If it is its own thing, I wonder if this could be a home for other ideas on project (vs. package) development. Of course, there could be other such packages out there (broadcasting my ignorance) - so perhaps these ideas could end up there.

At any rate, I thought to create this, in the short term, to take the "heat" off of usethis. 

You are all very welcome here.

My first thought was to start to sketch out an API:

---

```r
proj_create(
  path,
  rstudio = rstudioapi::isAvailable(),
  open = rlang::is_interactive(),
  fields = list()
)
```

This could call `usethis::create_project()`, then call `proj_use_description()`.

---

```r
proj_use_description(
  fields = list(),
  check_deps = TRUE
)
```

For an existing project, add a (denatured) DESCRIPTION file. Would call `usethis::use_description()`, then optionally call `proj_check_deps()`.

---

```r
proj_install_deps()
```

This would be a thin wrapper around `remotes::install_deps()`.

I can't see doing *anything* to the arguments - maybe just re-export instead?

---

```r
proj_check_deps()
```

This would be what is being discussed in r-lib/usethis#1194. It could check your listed dependencies against your actual dependencies, then let you know the difference. 

I like the idea of putting the names of packages to be added to `Imports:` into the clipboard, rather than modifying directly the DESCRIPTION.

---

```r
proj_use_github_action()
```

The GitHub Action would

- install R
- install the dependencies
- leave a "your instructions go here" part to invoke the building of your project (I won't know how....)

I think this could be a thin wrapper to `usethis::use_gihub_action()` that would provide the value to the `URL` argument.

**Comment by jennybc** [comment]
cc @Kevin_ushey

This is a discussion, that started in https://github.com/r-lib/usethis/issues/1194, that you might be interested in re: dependency management in non-package projects. Touches on the implicit vs explicit dependency issue.

**Comment by jennybc** [comment]
cc @kevinushey spelling the handle correctly this time

**Comment by ijlyttle** [comment]
Hello all,

After letting this marinate way too long, I have made a first implementation of this API, a [pkgdown site](https://ijlyttle.github.io/projthis/), and a [demonstration project](https://github.com/ijlyttle/projthis-demo).

If you all have any time to try it out and/or provide feedback, I would be very interested to hear what you might have to say.

Thanks!

**Comment by jennybc** [comment]
The pkgdown link doesn't seem to be working.

**Comment by jennybc** [comment]
I feel like I haven't thought about this in so long that it will take me a bit to recall the context and get my head in the right place.

**Comment by ijlyttle** [comment]
Fixed the pkgdown link - apologies and thanks!

The short version of the context is to imagine a project (not package) workflow where a `DESCRIPTION` file is used to declare package-dependencies. It assumes that a project will continue to "work" with the latest version of its package dependencies.

Following this assumption, some usethis-style functions are provided to:

- create a project with a `DESCRIPTION` file
- update the dependency declarations in the `DESCRIPTION` file

**Comment by ijlyttle** [comment]
Thinking a first API is more-or-less set now.
