### ISSUE TITLE
proj_check_deps()

### ISSUE THREAD

**Issue by ijlyttle** [ijlyttle/projthis#2]
Time to add some code.

Bouncing off of [this code](https://github.com/r-lib/usethis/issues/1194#issue-667655908) at usethis, this function will use:

- the current project, as understood by usethis.
- read the dependencies listed in the DESCRIPTION file, using `desc::desc_get_deps()`.
- determine the dependencies according to `renv::dependencies()`.
- provide feedback on missing and unused dependencies, and possibly add names of missing to clipboard.

Will need to figure out testing for this, perhaps set up some toy projects in the test directory, then use `usethis::with_project()` in the tests.

**Comment by elikesprogramming** [comment]
How do you feel about prompting the user to write/update to the DESCRIPTION file to include missing deps?, or perhaps an update_desc argument that defaults to FALSE?

**Comment by ijlyttle** [comment]
With a bulk update, I'm not entirely sure if a given package will belong in `Imports` or in `Suggests` - I suspect it will be `Imports`, but I am hesitant to make that choice instead of the user. I could be worrying about nothing.

We could create a companion function, `proj_update_deps()`, that does it all for you. Same logic as `proj_check_deps()`, but modify DESCRIPTION rather than write to clipboard.

**Comment by elikesprogramming** [comment]
`proj_update_deps()` sounds like a better approach. Regarding `Import` vs. `Suggests`, I would think most dependencies in most projects would be `Imports`, so I guess that should be the default. Then the users should manually change the few packages that (I think) would belong to `Suggests`. Perhaps `proj_update_deps()` can be a little chatty (usethis-style) and warn the user to do it, if that is the case.
