### ISSUE TITLE
update deps by default in proj_install_deps() and do not remove extra dependencies by default in proj_update_deps()

### ISSUE THREAD

**Issue by elikesprogramming** [ijlyttle/projthis#44]
wow!, {projthis} is great. Thanks for putting it together. `proj_update_deps()` and `proj_check_deps()` are awesome and very much what I had in mind when I opened my [issue](https://github.com/r-lib/usethis/issues/1194) in {usethis}.

Now, I have a couple of suggestions (sorry if I come somewhat late to the party. I did not have much time to take a look when you [opened the API discussion](https://github.com/ijlyttle/projthis/issues/1)).

1. I think it makes sense to let `proj_install_deps()` update the project dependencies before calling `remotes::install_deps`. In my view, that should be the default behaviour, and the user should be able to opt-out of it via an argument. Otherwise, it would be, well, a very very thin wrapper of its remotes counterpart.

2. `proj_update_deps()` should probably not remove extra dependencies by default. Dependencies discovery is not perfect (via `renv::dependencies()` or otherwise) and there might be a number of edge cases where `renv::dependencies()` fails to discover a relevant dependency.

   An example: I use {drake} in some of the projects where {projthis} shines and sometimes we use {qs} as the default format for 
storing the targets. To do this, you set the format argument to the string "qs"; `drake_config(plan, format = "qs")`. And nowhere else in the project the package {qs} is explicitly mentioned. Thus, `renv::dependencies()` does not find it as a dependency and ends up being removed from DESCRIPTION by `projthis::proj_update_deps()`. Yet, {qs} is actually needed and used internally by {drake}.

   And I am afraid those may not be just edge cases, but there might be actually quite a lot of them. So perhaps would be better to leave excluding dependencies as optional (something like `exclude = FALSE`), and keep just a warning for extra dependencies as `projthis::proj_check_deps()` does.

**Comment by ijlyttle** [comment]
@elikesprogramming You are right on time! Thanks for the thoughtful feedback. 

I will give these some thought. At first read, I like the idea of `proj_update_deps(exclude = FALSE)`.

I'll likely open some focused issues for the points you raise.

**Comment by ijlyttle** [comment]
Having had a good sleep and a coffee, I have split this into two new issues: #45 and #46

I get that `proj_install_deps()` is super thin, but I like keeping that as a separate function - instead to create a more-desciptively-named function: `proj_refresh_deps()`

Thanks again for the ideas, @elikesprogramming! Closing this one; please pipe in at the new issues, if you like.
